server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/springboot-realm-smartorder-dev/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:

        - id: orders-service
          uri: http://msvc-orders:8002
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: http://msvc-inventory:8004
          predicates:
            - Path=/api/inventory/**

        - id: products-service
          uri: http://msvc-products:8003
          predicates:
            - Path=/api/products/**

        - id: product-orders-service
          uri: http://msvc-products-orders:8005
          predicates:
            - Path=/api/products-orders/**

logging:
  level:
    org.springframework.security: DEBUG
